### ISSUE TITLE
Model disappearing from the screen in SceneViewer

### ISSUE THREAD

**Issue by MaksimRudyka** [google/model-viewer#2890]
Sorry that my English is not better.
After reducing the size of the model from huge, to the size we need. I ran into a problem playing the animation in the scene-viewer. In the first video you can see that the animation works as it should, in the second video the model just disappears after less than 22 seconds.

https://user-images.githubusercontent.com/74366254/137892208-a05765d0-e441-4de3-949c-43316c2d0ec6.mp4

https://user-images.githubusercontent.com/74366254/137892180-d172180a-0ae1-4d06-9276-5ce6a28f6eeb.mp4

The animation in the model itself lasts 10 minutes. But not in model-viewer nor in Windows 3D Viewer there are no such problems with animation.
Also the animation was checked with the gltf validator.

![image](https://user-images.githubusercontent.com/74366254/137892414-cc480a3f-30ea-469e-8035-32238ba4ac43.png)

If there are any ideas I will be glad to hear them.

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

-  [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [X] SceneViewer
- [ ] QuickLook

**Comment by MaksimRudyka** [comment]
Sure @eugenecys 
[gltf.zip](https://github.com/google/model-viewer/files/7389521/gltf.zip)

**Comment by MaksimRudyka** [comment]
Hi @eugenecys. Have you looked at the model yet?

**Comment by eugenecys** [comment]
Hi @MaksimRudyka, sorry for the late reply. I just downloaded the file you provided but I'm unable to unpack it. Can you either host the gltf somewhere or provide a compiled glb instead?

**Comment by MaksimRudyka** [comment]
Hi @eugenecys, I added the model to my Google Drive here's a link to the folder: https://drive.google.com/drive/folders/1MuVS6bs0QA8kgdDKIFd5jbl9PIVZnNeB?usp=sharing

**Comment by eugenecys** [comment]
Hi @MaksimRudyka, just want to provide an update, @AdrianAtGoogle is currently looking at it, there's a few unique things with your asset that we have not encountered before in other assets and he's trying to track them all down.

Current issues found and fixed:

- It has an armature of ~30 bones, and three different meshes each using the same skin (and sampling a unique subset of the bones).
- It has a plane whose vertices share exact heights, which was causing a zero-volume AABB to be computed.


Will let you know once all the fixes are rolled out

**Comment by AdrianAtGoogle** [comment]
Thank you for reporting this issue, it was tricky.  The asset was disappearing in Scene Viewer because of a [since-fixed issue](http://github.com/google/filament/pull/4889) in Filament's skinning code that was introducing nans. This fix will be rolled out to users over the next couple of weeks.

**Comment by MaksimRudyka** [comment]
Hello. How soon will your update for model-viewer with a fix for this bug.

**Comment by AdrianAtGoogle** [comment]
iOS release with this fix available as of 12/7, Android release was a couple of days earlier.

**Comment by elalish** [comment]
@MaksimRudyka this is not a model-viewer bug, but a scene-viewer bug, so there's no need to update model-viewer. As this update rolls out to Android/iOS users it will cease to repro.

**Comment by MaksimRudyka** [comment]
Hello.
I'm not a hundred percent sure I understood everything you wrote.
Do you mean that you will fixt it in scene-viewer and update it?
When can I see the changes and what do I need to do for this?
Could you give me some short instruction?
p.s I still see that an issue is reproduced.

**Comment by elalish** [comment]
@MaksimRudyka Yes, that's all correct. Have you checked  that your device  is fully updated? @AdrianAtGoogle It sounds like this  shouldn't repro anymore, right? Any thoughts?

**Comment by MaksimRudyka** [comment]
Hello @elalish. I'm still seeing this problem in scene-viewer. I have completely upgraded my device.

**Comment by AdrianAtGoogle** [comment]
Confirmed.  The model disappears later through the animation than it did with the previous regression, sorry about this; I'll see what is going on.

**Comment by AdrianAtGoogle** [comment]
A new fix is submitted and will roll out over the next few weeks.  Here's what I found out:

- The previous fix (from December) renders your asset correctly on iOS and Wasm, but not _Android in AR_.  I didn't test that last axis at the time 😔
- This turned out to be because our Android build compiles with `-ffast-math` for historical code-size related reasons and the others do not.
- Converting a 'nil' `filament::Aabb` (i.e. with `max` of FLT_MIN and a `min` of FLT_MAX) to a `filament::Box` (i.e. computing a center of `(max+min)/2`, half extents of `(max-min)/2`) will generate a half extent of `-inf` (this is what I fixed yesterday - now we emit a half extent of zero in that situation).
- Enabling `-ffast-math` means (among other things) that the optimizer can assume floats will never be infinity.
- When these `-inf`s in the extents are used to recompute the size of the shadow plane (which happens to be a parent of the rendered mesh in AR mode), with optimization settings that were told `inf` is impossible, `nan`s get introduced into the transform hierarchy.  These cause the hierarchy to stop rendering.

Sorry again about the delay in getting this properly addressed.
